config/routes.rb
Gitlab::Application.routes.draw do
  #
  # Search
  #
  get 'search' => "search#show"

  # API
  require 'api'
  mount Gitlab::API => '/api'

  # Optionally, enable Resque here
  require 'resque/server'
  mount Resque::Server.new, at: '/info/resque'

  # Enable Grack support
  mount Grack::Bundle.new({
    git_path:     Gitlab.config.git_bin_path,
    project_root: Gitlab.config.git_base_path,
    upload_pack:  Gitlab.config.git_upload_pack,
    receive_pack: Gitlab.config.git_receive_pack
  }), at: '/:path', constraints: { path: /[\w-]+\.git/ }

  #
  # Help
  #
  get 'help' => 'help#index'
  get 'help/permissions' => 'help#permissions'
  get 'help/workflow' => 'help#workflow'
  get 'help/api' => 'help#api'
  get 'help/web_hooks' => 'help#web_hooks'
  get 'help/system_hooks' => 'help#system_hooks'
  get 'help/markdown' => 'help#markdown'
  get 'help/ssh' => 'help#ssh'

  #
  # Admin Area
  #
  namespace :admin do
    resources :users do
      member do
        put :team_update
        put :block
        put :unblock
      end
    end
    resources :projects, :constraints => { :id => /[^\/]+/ } do
      member do
        get :team
        put :team_update
      end
    end
    resources :team_members, :only => [:edit, :update, :destroy]
    get 'mailer/preview_note'
    get 'mailer/preview_user_new'
    get 'mailer/preview_issue_new'

    resources :hooks, :only => [:index, :create, :destroy] do
      get :test
    end
    resource :logs
    resource :resque, :controller => 'resque'
    root :to => "dashboard#index"
  end

  get "errors/githost"

  #
  # Profile Area
  #
  get "profile/password", :to => "profile#password"
  put "profile/password", :to => "profile#password_update"
  get "profile/token", :to => "profile#token"
  put "profile/reset_private_token", :to => "profile#reset_private_token"
  get "profile", :to => "profile#show"
  get "profile/design", :to => "profile#design"
  put "profile/update", :to => "profile#update"
  resources :keys

  #
  # Dashboard Area
  #
  get "dashboard", :to => "dashboard#index"
  get "dashboard/issues", :to => "dashboard#issues"
  get "dashboard/merge_requests", :to => "dashboard#merge_requests"

  resources :projects, :constraints => { :id => /[^\/]+/ }, :only => [:new, :create]

  devise_for :users, :controllers => { :omniauth_callbacks => :omniauth_callbacks }

  #
  # Project Area
  #
  resources :projects, :constraints => { :id => /[^\/]+/ }, :except => [:new, :create, :index], :path => "/" do
    member do
      get "team"
      get "wall"
      get "graph"
      get "files"
    end

    resources :wikis, :only => [:show, :edit, :destroy, :create] do
      collection do
        get :pages
      end

      member do
        get "history"
      end
    end

    resource :repository do
      member do
        get "branches"
        get "tags"
        get "archive"
      end
    end

    resources :deploy_keys
    resources :protected_branches, :only => [:index, :create, :destroy]

    resources :refs, :only => [], :path => "/" do
      collection do
        get "switch"
      end

      member do
        get "tree", :constraints => { :id => /[a-zA-Z.\/0-9_\-]+/ }
        get "logs_tree", :constraints => { :id => /[a-zA-Z.\/0-9_\-]+/ }

        get "blob",
          :constraints => {
            :id => /[a-zA-Z.0-9\/_\-]+/,
            :path => /.*/
          }


        # tree viewer
        get "tree/:path" => "refs#tree",
          :as => :tree_file,
          :constraints => {
            :id => /[a-zA-Z.0-9\/_\-]+/,
            :path => /.*/
          }

        # tree viewer
        get "logs_tree/:path" => "refs#logs_tree",
          :as => :logs_file,
          :constraints => {
            :id => /[a-zA-Z.0-9\/_\-]+/,
            :path => /.*/
          }

        # blame
        get "blame/:path" => "refs#blame",
          :as => :blame_file,
          :constraints => {
            :id => /[a-zA-Z.0-9\/_\-]+/,
            :path => /.*/
          }
      end
    end

    resources :merge_requests do
      member do
        get :diffs
        get :automerge
        get :automerge_check
        get :raw
      end

      collection do
        get :branch_from
        get :branch_to
      end
    end

    resources :snippets do
      member do
        get "raw"
      end
    end

    resources :hooks, :only => [:index, :create, :destroy] do
      member do
        get :test
      end
    end
    resources :commits do
      collection do
        get :compare
      end

      member do
        get :patch
      end
    end
    resources :team_members
    resources :milestones
    resources :issues do
      collection do
        post  :sort
        post  :bulk_update
        get   :search
      end
    end
    resources :notes, :only => [:index, :create, :destroy] do
      collection do
        post :preview
      end
    end
  end
  root :to => "dashboard#index"
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  include IssueCommonality
  include Upvote

  acts_as_taggable_on :labels

  belongs_to :milestone

  validates :description,
            length: { within: 0..2000 }

  def self.open_for(user)
    opened.assigned(user)
  end

  def is_assigned?
    !!assignee_id
  end

  def is_being_reassigned?
    assignee_id_changed?
  end

  def is_being_closed?
    closed_changed? && closed
  end

  def is_being_reopened?
    closed_changed? && !closed
  end
end
# == Schema Information
#
# Table name: issues
#
#  id           :integer(4)      not null, primary key
#  title        :string(255)
#  assignee_id  :integer(4)
#  author_id    :integer(4)
#  project_id   :integer(4)
#  created_at   :datetime        not null
#  updated_at   :datetime        not null
#  closed       :boolean(1)      default(FALSE), not null
#  position     :integer(4)      default(0)
#  critical     :boolean(1)      default(FALSE), not null
#  branch_name  :string(255)
#  description  :text
#  milestone_id :integer(4)
#

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :project
  before_filter :module_enabled
  before_filter :issue, only: [:edit, :update, :destroy, :show]
  helper_method :issues_filter

  layout "project"

  # Authorize
  before_filter :add_project_abilities

  # Allow read any issue
  before_filter :authorize_read_issue!

  # Allow write(create) issue
  before_filter :authorize_write_issue!, only: [:new, :create]

  # Allow modify issue
  before_filter :authorize_modify_issue!, only: [:close, :edit, :update]

  # Allow destroy issue
  before_filter :authorize_admin_issue!, only: [:destroy]

  respond_to :js, :html

  def index
    @issues = issues_filtered

    @issues = @issues.page(params[:page]).per(20)

    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.atom { render layout: false }
    end
  end

  def new
    @issue = @project.issues.new
    respond_with(@issue)
  end

  def edit
    respond_with(@issue)
  end

  def show
    @note = @project.notes.new(noteable: @issue)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @issue = @project.issues.new(params[:issue])
    @issue.author = current_user
    @issue.save

    respond_to do |format|
      format.html { redirect_to project_issue_path(@project, @issue) }
      format.js
    end
  end

  def update
    @issue.update_attributes(params[:issue].merge(author_id_of_changes: current_user.id))

    respond_to do |format|
      format.js
      format.html do 
        if @issue.valid?
          redirect_to [@project, @issue]
        else
          render :edit
        end
      end
    end
  end

  def destroy
    return access_denied! unless can?(current_user, :admin_issue, @issue)

    @issue.destroy

    respond_to do |format|
      format.html { redirect_to project_issues_path }
      format.js { render nothing: true }
    end
  end

  def sort
    return render_404 unless can?(current_user, :admin_issue, @project)

    @issues = @project.issues.where(id: params['issue'])
    @issues.each do |issue|
      issue.position = params['issue'].index(issue.id.to_s) + 1
      issue.save
    end

    render nothing: true
  end

  def search
    terms = params['terms']

    @issues = issues_filtered
    @issues = @issues.where("title LIKE ?", "%#{terms}%") unless terms.blank?
    @issues = @issues.page(params[:page]).per(100)

    render partial: 'issues'
  end

  def bulk_update
    result = IssuesBulkUpdateContext.new(project, current_user, params).execute
    redirect_to :back, notice: "#{result[:count]} issues updated"
  end

  protected

  def issue
    @issue ||= @project.issues.find(params[:id])
  end

  def authorize_modify_issue!
    return render_404 unless can?(current_user, :modify_issue, @issue)
  end

  def authorize_admin_issue!
    return render_404 unless can?(current_user, :admin_issue, @issue)
  end

  def module_enabled
    return render_404 unless @project.issues_enabled
  end

  def issues_filtered
    @issues = case params[:f]
              when issues_filter[:all] then @project.issues
              when issues_filter[:closed] then @project.issues.closed
              when issues_filter[:to_me] then @project.issues.opened.assigned(current_user)
              else @project.issues.opened
              end

    @issues = @issues.tagged_with(params[:label_name]) if params[:label_name].present?
    @issues = @issues.includes(:author, :project).order("updated_at")

    # Filter by specific assignee_id (or lack thereof)?
    if params[:assignee_id].present?
      @issues = @issues.where(assignee_id: (params[:assignee_id] == '0' ? nil : params[:assignee_id]))
    end

    # Filter by specific milestone_id (or lack thereof)?
    if params[:milestone_id].present?
      @issues = @issues.where(milestone_id: (params[:milestone_id] == '0' ? nil : params[:milestone_id]))
    end

    @issues
  end

  def issues_filter
    {
      all: "1",
      closed: "2",
      to_me: "3",
      open: "0" 
    }
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
  def project_issues_filter_path project, params = {}
    params[:f] ||= cookies['issue_filter']
    project_issues_path project, params
  end

  def link_to_issue_assignee(issue)
    project = issue.project

    tm = project.team_member_by_id(issue.assignee_id)
    if tm
      link_to issue.assignee_name, project_team_member_path(project, tm), class: "author_link"
    else
      issue.assignee_name
    end
  end

  def link_to_issue_author(issue)
    project = issue.project

    tm = project.team_member_by_id(issue.author_id)
    if tm
      link_to issue.author_name, project_team_member_path(project, tm), class: "author_link"
    else
      issue.author_name
    end
  end

  def issue_css_classes issue
    classes = "issue"
    classes << " closed" if issue.closed
    classes << " today" if issue.today?
    classes
  end

  def issue_tags 
    @project.issues.tag_counts_on(:labels).map(&:name)
  end

  # Returns an OpenStruct object suitable for use by <tt>options_from_collection_for_select</tt>
  # to allow filtering issues by an unassigned User or Milestone
  def unassigned_filter
    # Milestone uses :title, Issue uses :name
    OpenStruct.new(id: 0, title: 'Unspecified', name: 'Unassigned')
  end
end

app/views/issues/_form.html.haml
%div.issue-form-holder
  %h3.page_title= @issue.new_record? ? "New Issue" : "Edit Issue ##{@issue.id}"
  = form_for [@project, @issue], remote: request.xhr? do |f|
    -if @issue.errors.any?
      .alert-message.block-message.error
        %ul
          - @issue.errors.full_messages.each do |msg|
            %li= msg
    .issue_form_box
      .issue_title
        .clearfix
          = f.label :title do
            %strong= "Subject *"
          .input
            = f.text_field :title, maxlength: 255, class: "xxlarge"
      .issue_middle_block
        .issue_assignee
          = f.label :assignee_id do
            %i.icon-user
            Assign to
          .input= f.select(:assignee_id, @project.users.all.collect {|p| [ p.name, p.id ] }, { include_blank: "Select a user" })
        .issue_milestone
          = f.label :milestone_id do
            %i.icon-time
            Milestone
          .input= f.select(:milestone_id, @project.milestones.active.all.collect {|p| [ p.title, p.id ] }, { include_blank: "Select milestone" })

      .issue_description
        .clearfix
          = f.label :label_list do
            %i.icon-tag
            Labels
          .input
            = f.text_field :label_list, maxlength: 2000, class: "xxlarge"
            %p.hint Separate with comma.

        .clearfix
          = f.label :description, "Details"
          .input
            = f.text_area :description, maxlength: 2000, class: "xxlarge", rows: 14
            %p.hint Markdown is enabled.


    .actions
      - if @issue.new_record?
        = f.submit 'Submit new issue', class: "primary btn"
      -else
        = f.submit 'Save changes', class: "primary btn"

      - if request.xhr?
        = link_to "Cancel", "#back", onclick: "backToIssues();", class: "btn"
      - else
        - if @issue.new_record?
          = link_to "Cancel", project_issues_path(@project), class: "btn"
        - else
          = link_to "Cancel", project_issue_path(@project, @issue), class: "btn"

app/views/issues/_head.html.haml
%ul.nav.nav-tabs
  %li{class: "#{'active' if current_page?(project_issues_path(@project))}"}
    = link_to project_issues_path(@project), class: "tab" do
      Browse Issues
  %li{class: "#{'active' if current_page?(project_milestones_path(@project))}"}
    = link_to project_milestones_path(@project), class: "tab" do
      Milestones
  %li.right
    %span.rss-icon
      = link_to project_issues_path(@project, :atom, { private_token: current_user.private_token }) do
        = image_tag "rss_ui.png", title: "feed"

app/views/issues/_issues.html.haml
- @issues.each do |issue|
  = render(partial: 'issues/show', locals: {issue: issue})

- if @issues.present?
  %li.bottom
    .row
      .span7= paginate @issues, remote: true, theme: "gitlab"
      .span3.right
        %span.cgray.right 
          %span.issue_counter #{@issues.total_count}
          issues for this filter
- else
  %li
    %h4.nothing_here_message Nothing to show here

app/views/issues/_show.html.haml
%li.wll{ id: dom_id(issue), class: issue_css_classes(issue), url: project_issue_path(issue.project, issue) }
  - if controller.controller_name == 'issues'
    .issue_check
      = check_box_tag dom_id(issue,"selected"), nil, false, 'data-id' => issue.id, class: "selected_issue", disabled: !can?(current_user, :modify_issue, issue)
  .right
    - issue.labels.each do |label|
      %span.label.label-issue.grouped
        %i.icon-tag
        = label.name
    - if issue.notes.any?
      %span.btn.small.disabled.grouped
        %i.icon-comment
        = issue.notes.count
    - if can? current_user, :modify_issue, issue
      - if issue.closed
        = link_to 'Reopen', project_issue_path(issue.project, issue, issue: {closed: false }, status_only: true), method: :put,  class: "btn small grouped reopen_issue", remote: true
      - else
        = link_to 'Resolve', project_issue_path(issue.project, issue, issue: {closed: true }, status_only: true), method: :put, class: "success btn small grouped close_issue", remote: true
      = link_to edit_project_issue_path(issue.project, issue), class: "btn small edit-issue-link", remote: true do
        %i.icon-edit
        Edit

  - if issue.assignee
    = image_tag gravatar_icon(issue.assignee_email), class: "avatar"
  - else
    = image_tag "no_avatar.png", class: "avatar"

  %p= link_to_gfm truncate(issue.title, length: 100), project_issue_path(issue.project, issue), class: "row_title"

  %span.update-author
    %small.cdark= "##{issue.id}"
    - if issue.assignee
      assigned to #{issue.assignee_name}
    - else
      &nbsp;

    - if issue.upvotes > 0
      %span.badge.badge-success= "+#{issue.upvotes}"

app/views/issues/create.js.haml
- if @issue.valid?
  :plain
    switchFromNewIssue();
    $("#issues-table").prepend("#{escape_javascript(render(partial: 'show', locals: {issue: @issue}))}");
    $.ajax({type: "GET", url: location.href, dataType: "script"});
- else
  :plain
    $("#new_issue_dialog").empty();
    $("#new_issue_dialog").append("#{escape_javascript(render('form'))}");
    $('select#issue_assignee_id').chosen();

app/views/issues/edit.html.haml
= render "form"

:javascript
  $(function(){
    $('select#issue_assignee_id').chosen();
    $('select#issue_milestone_id').chosen();
  });

app/views/issues/edit.js.haml
:plain
  var edit_issue_dialog = $("<div id='edit_issue_dialog'></div>");
  edit_issue_dialog.html("#{escape_javascript(render('form'))}");
  switchToEditIssue(edit_issue_dialog);

app/views/issues/index.html.haml
= render "issues/head"
.issues_content
  %h3.page_title
    Issues
    %small (<span class=issue_counter>#{@issues.total_count}</span>)
    .right
      .span5
        - if can? current_user, :write_issue, @project
          = link_to new_project_issue_path(@project), class: "right btn small", title: "New Issue", remote: true do
            %i.icon-plus
            New Issue
        = form_tag search_project_issues_path(@project), method: :get, remote: true, id: "issue_search_form", class: :right  do
          = hidden_field_tag :project_id, @project.id, { id: 'project_id' }
          = hidden_field_tag :status, params[:f]
          = search_field_tag :issue_search, nil, { placeholder: 'Search', class: 'issue_search span3 right neib' }

  .clearfix

  %div#issues-table-holder.ui-box
    .title
      = check_box_tag "check_all_issues", nil, false, class: "check_all_issues left"


      .issues_bulk_update.hide
        = form_tag bulk_update_project_issues_path(@project), method: :post  do
          %span.update_issues_text Update selected issues with &nbsp;
          .left
            = select_tag('update[status]', options_for_select(['open', 'closed']), prompt: "Status")
            = select_tag('update[assignee_id]', options_from_collection_for_select(@project.users.all, "id", "name", params[:assignee_id]), prompt: "Assignee")
            = select_tag('update[milestone_id]', options_from_collection_for_select(@project.milestones.order("id desc").all, "id", "title", params[:milestone_id]), prompt: "Milestone")
            = hidden_field_tag 'update[issues_ids]', []
            = hidden_field_tag :f, params[:f]
          = button_tag "Save", class: "btn update_selected_issues"
      .issues_filters
        .left
          %ul.nav.nav-pills.left
            %li{class: ("active" if (params[:f] == issues_filter[:open] || !params[:f]))}
              = link_to project_issues_path(@project, f: issues_filter[:open], milestone_id: params[:milestone_id]) do
                Open
            %li{class: ("active" if params[:f] == issues_filter[:closed])}
              = link_to project_issues_path(@project, f: issues_filter[:closed], milestone_id: params[:milestone_id]) do
                Closed
            %li{class: ("active" if params[:f] == issues_filter[:to_me])}
              = link_to project_issues_path(@project, f: issues_filter[:to_me], milestone_id: params[:milestone_id]) do
                To Me
            %li{class: ("active" if params[:f] == issues_filter[:all])}
              = link_to project_issues_path(@project, f: issues_filter[:all], milestone_id: params[:milestone_id]) do
                All

        .right
          = form_tag project_issues_path(@project), method: :get, class: :right  do
            = select_tag(:label_name, options_for_select(issue_tags, params[:label_name]), prompt: "Labels")
            = select_tag(:assignee_id, options_from_collection_for_select([unassigned_filter] + @project.users.all, "id", "name", params[:assignee_id]), prompt: "Assignee")
            = select_tag(:milestone_id, options_from_collection_for_select([unassigned_filter] + @project.milestones.order("id desc").all, "id", "title", params[:milestone_id]), prompt: "Milestone")
            = hidden_field_tag :f, params[:f]
        .clearfix

    %ul#issues-table.unstyled.issues_table
      = render "issues"


:javascript
  $(function(){
    issuesPage();
  })

app/views/issues/index.js.haml
:plain
  $('#issues-table').html("#{escape_javascript(render('issues'))}");

app/views/issues/new.html.haml
= render "form"

:javascript
  $(function(){
    $('select#issue_assignee_id').chosen();
    $('select#issue_milestone_id').chosen();
  });

app/views/issues/new.js.haml
:plain
  var new_issue_dialog = $("<div id='new_issue_dialog'></div>");
  new_issue_dialog.html("#{escape_javascript(render('form'))}");
  switchToNewIssue(new_issue_dialog);

app/views/issues/show.html.haml
%h3.page_title
  Issue ##{@issue.id}

  %small
    created at
    = @issue.created_at.stamp("Aug 21, 2011")

  %span.right
    - if can?(current_user, :admin_project, @project) || @issue.author == current_user
      - if @issue.closed
        = link_to 'Reopen', project_issue_path(@project, @issue, issue: {closed: false }, status_only: true), method: :put,  class: "btn small"
      - else
        = link_to 'Close', project_issue_path(@project, @issue, issue: {closed: true }, status_only: true), method: :put, class: "btn small", title: "Close Issue"
    - if can?(current_user, :admin_project, @project) || @issue.author == current_user
      = link_to edit_project_issue_path(@project, @issue), class: "btn small" do
        %i.icon-edit
        Edit

    %br
    - if @issue.upvotes > 0
      .upvotes#upvotes= "+#{pluralize @issue.upvotes, 'upvote'}"

.back_link
  = link_to project_issues_path(@project) do
    &larr; To issues list

.main_box
  .top_box_content
    %h4
      - if @issue.closed
        .alert-message.error.status_info Closed
      - else
        .alert-message.success.status_info Open
      = gfm @issue.title

  .middle_box_content
    %cite.cgray Created by
    = image_tag gravatar_icon(@issue.author_email), width: 16, class: "lil_av"
    %strong.author= link_to_issue_author(@issue)

    - if @issue.assignee
      %cite.cgray and currently assigned to
      = image_tag gravatar_icon(@issue.assignee_email), width: 16, class: "lil_av"
      %strong.author= link_to_issue_assignee(@issue)

    - if @issue.milestone
      - milestone = @issue.milestone
      %cite.cgray and attached to milestone
      %strong= link_to_gfm truncate(milestone.title, length: 20), project_milestone_path(milestone.project, milestone)

    .right
      - @issue.labels.each do |label|
        %span.label.label-issue
          %i.icon-tag
          = label.name
        &nbsp;

  - if @issue.description.present?
    .bottom_box_content
      = preserve do
        = markdown @issue.description


.issue_notes#notes= render "notes/notes", tid: @issue.id, tt: "issue"

app/views/issues/update.js.haml
- if params[:status_only]
  - if @issue.valid?
    :plain
      $("##{dom_id(@issue)}").fadeOut();
- else
  - if @issue.valid?
    :plain
      updatePage();
      switchFromEditIssue();
  - else
    :plain
      $("#edit_issue_dialog").empty();
      $("#edit_issue_dialog").append("#{escape_javascript(render('form'))}");
      $('select#issue_assignee_id').chosen();