config/routes.rb
Gitlab::Application.routes.draw do
  #
  # Search
  #
  get 'search' => "search#show"

  # API
  require 'api'
  mount Gitlab::API => '/api'

  # Optionally, enable Resque here
  require 'resque/server'
  mount Resque::Server.new, at: '/info/resque'

  # Enable Grack support
  mount Grack::Bundle.new({
    git_path:     Gitlab.config.git_bin_path,
    project_root: Gitlab.config.git_base_path,
    upload_pack:  Gitlab.config.git_upload_pack,
    receive_pack: Gitlab.config.git_receive_pack
  }), at: '/:path', constraints: { path: /[\w-]+\.git/ }

  #
  # Help
  #
  get 'help' => 'help#index'
  get 'help/permissions' => 'help#permissions'
  get 'help/workflow' => 'help#workflow'
  get 'help/api' => 'help#api'
  get 'help/web_hooks' => 'help#web_hooks'
  get 'help/system_hooks' => 'help#system_hooks'
  get 'help/markdown' => 'help#markdown'
  get 'help/ssh' => 'help#ssh'

  #
  # Admin Area
  #
  namespace :admin do
    resources :users do
      member do
        put :team_update
        put :block
        put :unblock
      end
    end
    resources :projects, :constraints => { :id => /[^\/]+/ } do
      member do
        get :team
        put :team_update
      end
    end
    resources :team_members, :only => [:edit, :update, :destroy]
    get 'mailer/preview_note'
    get 'mailer/preview_user_new'
    get 'mailer/preview_issue_new'

    resources :hooks, :only => [:index, :create, :destroy] do
      get :test
    end
    resource :logs
    resource :resque, :controller => 'resque'
    root :to => "dashboard#index"
  end

  get "errors/githost"

  #
  # Profile Area
  #
  get "profile/password", :to => "profile#password"
  put "profile/password", :to => "profile#password_update"
  get "profile/token", :to => "profile#token"
  put "profile/reset_private_token", :to => "profile#reset_private_token"
  get "profile", :to => "profile#show"
  get "profile/design", :to => "profile#design"
  put "profile/update", :to => "profile#update"
  resources :keys

  #
  # Dashboard Area
  #
  get "dashboard", :to => "dashboard#index"
  get "dashboard/issues", :to => "dashboard#issues"
  get "dashboard/merge_requests", :to => "dashboard#merge_requests"

  resources :projects, :constraints => { :id => /[^\/]+/ }, :only => [:new, :create]

  devise_for :users, :controllers => { :omniauth_callbacks => :omniauth_callbacks }

  #
  # Project Area
  #
  resources :projects, :constraints => { :id => /[^\/]+/ }, :except => [:new, :create, :index], :path => "/" do
    member do
      get "team"
      get "wall"
      get "graph"
      get "files"
    end

    resources :wikis, :only => [:show, :edit, :destroy, :create] do
      collection do
        get :pages
      end

      member do
        get "history"
      end
    end

    resource :repository do
      member do
        get "branches"
        get "tags"
        get "archive"
      end
    end

    resources :deploy_keys
    resources :protected_branches, :only => [:index, :create, :destroy]

    resources :refs, :only => [], :path => "/" do
      collection do
        get "switch"
      end

      member do
        get "tree", :constraints => { :id => /[a-zA-Z.\/0-9_\-]+/ }
        get "logs_tree", :constraints => { :id => /[a-zA-Z.\/0-9_\-]+/ }

        get "blob",
          :constraints => {
            :id => /[a-zA-Z.0-9\/_\-]+/,
            :path => /.*/
          }


        # tree viewer
        get "tree/:path" => "refs#tree",
          :as => :tree_file,
          :constraints => {
            :id => /[a-zA-Z.0-9\/_\-]+/,
            :path => /.*/
          }

        # tree viewer
        get "logs_tree/:path" => "refs#logs_tree",
          :as => :logs_file,
          :constraints => {
            :id => /[a-zA-Z.0-9\/_\-]+/,
            :path => /.*/
          }

        # blame
        get "blame/:path" => "refs#blame",
          :as => :blame_file,
          :constraints => {
            :id => /[a-zA-Z.0-9\/_\-]+/,
            :path => /.*/
          }
      end
    end

    resources :merge_requests do
      member do
        get :diffs
        get :automerge
        get :automerge_check
        get :raw
      end

      collection do
        get :branch_from
        get :branch_to
      end
    end

    resources :snippets do
      member do
        get "raw"
      end
    end

    resources :hooks, :only => [:index, :create, :destroy] do
      member do
        get :test
      end
    end
    resources :commits do
      collection do
        get :compare
      end

      member do
        get :patch
      end
    end
    resources :team_members
    resources :milestones
    resources :issues do
      collection do
        post  :sort
        post  :bulk_update
        get   :search
      end
    end
    resources :notes, :only => [:index, :create, :destroy] do
      collection do
        post :preview
      end
    end
  end
  root :to => "dashboard#index"
end

app/controllers/admin/team_members_controller.rb
class Admin::TeamMembersController < ApplicationController
  layout "admin"
  before_filter :authenticate_user!
  before_filter :authenticate_admin!

  def edit
    @admin_team_member = UsersProject.find(params[:id])
  end

  def update
    @admin_team_member = UsersProject.find(params[:id])

    if @admin_team_member.update_attributes(params[:team_member])
      redirect_to [:admin, @admin_team_member.project],  notice: 'Project Access was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @admin_team_member = UsersProject.find(params[:id])
    @admin_team_member.destroy

    redirect_to :back
  end
end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  before_filter :project
  layout "project"

  # Authorize
  before_filter :add_project_abilities
  before_filter :authorize_read_project!
  before_filter :authorize_admin_project!, except: [:show]

  def show
    @team_member = project.users_projects.find(params[:id])
    @events = @team_member.user.recent_events.where(:project_id => @project.id).limit(7)
  end

  def new
    @team_member = project.users_projects.new
  end

  def create
    @team_member = UsersProject.new(params[:team_member])
    @team_member.project = project
    if @team_member.save
      redirect_to team_project_path(@project)
    else
      render "new"
    end
  end

  def update
    @team_member = project.users_projects.find(params[:id])
    @team_member.update_attributes(params[:team_member])

    unless @team_member.valid?
      flash[:alert] = "User should have at least one role"
    end
    redirect_to team_project_path(@project)
  end

  def destroy
    @team_member = project.users_projects.find(params[:id])
    @team_member.destroy

    respond_to do |format|
      format.html { redirect_to team_project_path(@project) }
      format.js { render nothing: true }
    end
  end
end

app/views/team_members/_form.html.haml
%h3= "New Team member"
%hr
= form_for @team_member, as: :team_member, url: project_team_members_path(@project, @team_member) do |f|
  -if @team_member.errors.any?
    .alert-message.block-message.error
      %ul
        - @team_member.errors.full_messages.each do |msg|
          %li= msg

  .clearfix
    = f.label :user_id, "Name"
    .input= f.select(:user_id, User.not_in_project(@project).all.collect {|p| [ p.name, p.id ] }, { include_blank: "Select user" }, { style: "width:300px" })


  .clearfix
    = f.label :project_access, "Project Access"
    .input= f.select :project_access, options_for_select(Project.access_options, @team_member.project_access), {}, class: "project-access-select"


  .actions
    = f.submit 'Save', class: "btn primary"
    = link_to "Cancel", team_project_path(@project), class: "btn"

:css
  form select {
    width:300px;
  }

:javascript
  $('select#team_member_user_id').chosen();
  $('select#team_member_project_access').chosen();
  //$('select#team_member_repo_access').chosen();
  //$('select#team_member_project_access').chosen();

app/views/team_members/_show.html.haml
- user = member.user
- allow_admin = can? current_user, :admin_project, @project
%tr{id: dom_id(member), class: "team_member_row user_#{user.id}"}
  %td
    .right
      - if @project.owner == user
        %span.label Project Owner
      - if user.blocked
        %span.label Blocked

    = link_to project_team_member_path(@project, member), title: user.name, class: "dark" do
      = image_tag gravatar_icon(user.email, 40), class: "avatar s32"
    = link_to project_team_member_path(@project, member), title: user.name, class: "dark" do
      %strong= truncate(user.name, lenght: 40)
    %br
    %div.cgray= user.email

  %td
    = form_for(member, as: :team_member, url: project_team_member_path(@project, member)) do |f|
      = f.select :project_access, options_for_select(UsersProject.access_roles, member.project_access), {}, class: "medium project-access-select", disabled: !allow_admin

app/views/team_members/create.js.haml
- if @team_member.valid?
  :plain
    $("#new_team_member").hide("slide", { direction: "right" }, 150, function(){
      $("#team-table").show("slide", { direction: "left" }, 150, function() {
        $("#new_team_member").remove();
        $("#team-table").replaceWith("#{escape_javascript(render('projects/team'))}");
        $(".add_new").show();
      });
    });
- else
  :plain
    $("#new_team_member").replaceWith("#{escape_javascript(render('form'))}");
    $('select#team_member_user_id').chosen();

app/views/team_members/new.html.haml
= render "projects/project_head"
= render "team_members/form"

app/views/team_members/show.html.haml
- allow_admin = can? current_user, :admin_project, @project
- user = @team_member.user

.team_member_show
  - if can? current_user, :admin_project, @project
    = link_to 'Remove from team', project_team_member_path(project_id: @project, id: @team_member.id), confirm: 'Are you sure?', method: :delete, class: "right btn btn-danger"
  .profile_avatar_holder
    = image_tag gravatar_icon(user.email, 60), class: "borders"
  %h3
    = user.name
    %small
      = user.email

  %hr
  .back_link
    %br
    = link_to team_project_path(@project), class: "" do
      &larr; To team list
  %br
  .row
    .span6
      %table.no-borders
        %tr
          %td Email
          %td= mail_to user.email
        %tr
          %td Skype
          %td= user.skype
        - unless user.linkedin.blank?
          %tr
            %td LinkedIn
            %td= user.linkedin
        - unless user.twitter.blank?
          %tr
            %td Twitter
            %td= user.twitter
        - unless user.bio.blank?
          %tr
            %td Bio
            %td= user.bio
    .span6
      %table.no-borders
        %tr
          %td Member since
          %td= @team_member.created_at.stamp("Aug 21, 2011")
        %tr
          %td
            Project Access:
            %small (#{link_to "read more", help_permissions_path, class: "vlink"})
          %td
            = form_for(@team_member, as: :team_member, url: project_team_member_path(@project, @team_member)) do |f|
              = f.select :project_access, options_for_select(Project.access_options, @team_member.project_access), {}, class: "project-access-select", disabled: !allow_admin
  %hr
  = render @events
:javascript
  $(function(){
    $('.repo-access-select, .project-access-select').live("change", function() {
      $(this.form).submit();
    });
  })

app/views/team_members/update.js.haml
- if @team_member.valid?
  :plain
    $("##{dom_id(@team_member)}").effect("highlight", {color: "#529214"}, 1000);;
- else
  :plain
    $("##{dom_id(@team_member)}").effect("highlight", {color: "#D12F19"}, 1000);;